name: Generate Snake (Matrix Style)

on:
  schedule:
    - cron: "0 */12 * * *"   # a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Generate Matrix Snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          color_snake: "#00ff00"
          color_head: "#00ff55"
          color_dot: "#00000088"
          color_background: "#000000"
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List generated files
        run: ls -la dist

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update Matrix Snake animations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



